### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by PhenixWen** [mcauser/BLUE_PILL_F103C8#1]
i get following problem when compile it:

phenix@phenix:~/micropython/micropython/ports/stm32$ make BOARD=BLUE_PILL_F103C8 deploy
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make: *** 没有规则可以创建“build-BLUE_PILL_F103C8/py/mpstate.o”需要的目标“build-BLUE_PILL_F103C8/genhdr/pins.h”。 停止。
phenix@phenix:~/micropython/micropython/ports/stm32$ make BOARD=BLUE_PILL_F103C8
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make: *** 没有规则可以创建“build-BLUE_PILL_F103C8/py/mpstate.o”需要的目标“build-BLUE_PILL_F103C8/genhdr/pins.h”。 停止。
phenix@phenix:~/micropython/micropython/ports/stm32$ 
phenix@phenix:~/micropython/micropython/ports/stm32$ 
phenix@phenix:~/micropython/micropython/ports/stm32$ 
phenix@phenix:~/micropython/micropython/ports/stm32$ 
phenix@phenix:~/micropython/micropython/ports/stm32$ 
phenix@phenix:~/micropython/micropython/ports/stm32$ make BOARD=BLUE_PILL_F103C8 deploy
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make: *** 没有规则可以创建“build-BLUE_PILL_F103C8/py/mpstate.o”需要的目标“build-BLUE_PILL_F103C8/genhdr/pins.h”。 停止。
phenix@phenix:~/micropython/micropython/ports/stm32$ 
phenix@phenix:~/micropython/micropython/ports/stm32$ 
phenix@phenix:~/micropython/micropython/ports/stm32

**Comment by mcauser** [comment]
This board def does not compile.

STM32F1 support has not been added to MicroPython yet.
There's a bunch of `if defined` statements that need to be added everywhere.
eg. https://github.com/micropython/micropython/blob/4a93801c12898898744131f57d79cf216d0861b3/ports/stm32/dma.c#L56

**Comment by PhenixWen** [comment]
Do you have a project which can be compile correctly?

**Comment by mcauser** [comment]
No. It’s a work in progress.

**Comment by PhenixWen** [comment]
oops, it's a long hard work.

**Comment by JIMhackKING** [comment]
I've get this problem too, where I need to modify to, which file need modify?

**Comment by mcauser** [comment]
Lots of files. It's not finished yet

**Comment by JIMhackKING** [comment]
Oh, Thank you for your hard work.

**Comment by japuzzo** [comment]
Still an issue:

$ date ; make BOARD=BLUE_PILL_F103C8
Fri Apr 13 21:33:10 EDT 2018
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make: *** No rule to make target `build-BLUE_PILL_F103C8/genhdr/pins.h', needed by `build-BLUE_PILL_F103C8/py/mpstate.o'.  Stop.

So is this project defunct?
Where else should I look for a solution?
How can I help?

**Comment by mcauser** [comment]
**This project is not finished.**
This board def does not compile.
STM32F1 support has not been added to MicroPython yet.

If you would like to use your STM32F103 board, perhaps go down the Arduino path: http://www.stm32duino.com/viewforum.php?f=1
