### ISSUE TITLE
What can we do with this?

### ISSUE THREAD

**Issue by Cheaterman** [mcauser/BLUE_PILL_F103C8#2]
Hello my friend and thanks for the magic!

What can we expect to be able to do with this if it ever works? I'm particularly concerned with the quantity of RAM available on the chip :-3 I feel like it's going to be complicated to run more than a "Hello, World!" on 20KiB? How much do you need to strip down `mpy` (which features do you need to sacrifice) to make it fit on 128KiB of flash? etc :-)

Thanks in advance!

**Comment by mcauser** [comment]
It's very early days in the project. So far, it's a learning experience for running a "Hello, World!".

I'm also working on a version for the F103RET6, which 512k flash and 64k sram
https://github.com/mcauser/BLUE_BUTTON_F103RET6
Lots of F103 work needs to happen first...

Added the cube fw:
https://github.com/mcauser/stm32lib/commits/vendor-F1-1.6.0

**Comment by Cheaterman** [comment]
Thanks for the info :-) sounds goodie! I have a F103C8 myself and was wondering if I could at least get a serial REPL, maybe light up some LEDs or things like that - nothing too fancy really, just for fun. Hopefully some people will get interested and contribute :-)
