### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by jiangluorng** [mcauser/BLUE_PILL_F103C8#3]
When I complie follow your according to your instructions, I meet the following problem:
__________________________
$ make BOARD=BLUE_PILL_F103C8
__________________________
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make: *** No rule to make target 'build-BLUE_PILL_F103C8/genhdr/pins.h', needed by 'build-BLUE_PILL_F103C8/py/mpstate.o'.  Stop.
__________________________

Is there any solutions to solve this problem?

**Comment by mcauser** [comment]
This project is not finished and does not build.

**Comment by stappersg** [comment]
In https://forum.micropython.org/viewtopic.php?t=3813&start=10#p24085 is a report of a succesfull build.
(however meanwhile is that succes a year old)

**Comment by mcauser** [comment]
Still needs lots of work to get the F103C8 working...

In the meantime, check out the more powerful F407VET6 board from Vcc-gnd on Taobao: https://github.com/mcauser/VCC_GND_F407
Same guys that make the "blue pill".
